require('dotenv').config();
const mongoose    = require('mongoose');
const User        = require('./models/User');
const Patient     = require('./models/Patient');
const Doctor      = require('./models/Doctor');
const Prescription= require('./models/Prescription');
const Consultation= require('./models/Consultation');
const Message     = require('./models/Message');
const { users, patientProfiles, doctorProfiles } = require('./utils/seed');
const logger      = require('./utils/logger');

const connect = async () => {
  await mongoose.connect(process.env.MONGODB_URI || 'mongodb://localhost:27017/medilink');
  logger.info('MongoDB connected for seeding');
};

const seedData = async () => {
  logger.info('Seeding database…');

  // Users: insertMany is fine — password is already hashed in seed data,
  // and pre-save hook only re-hashes if password is modified (isModified check).
  // But insertMany bypasses pre-save entirely, which is what we want here.
  const insertedUsers = await User.insertMany(users, { ordered: true });
  logger.info(`Inserted ${insertedUsers.length} users`);

  const userIds       = insertedUsers.map(u => u._id);
  const patientData   = patientProfiles(userIds);
  const doctorData    = doctorProfiles(userIds);

  const insertedPatients = await Patient.insertMany(patientData);
  logger.info(`Inserted ${insertedPatients.length} patient profiles`);

  const insertedDoctors  = await Doctor.insertMany(doctorData);
  logger.info(`Inserted ${insertedDoctors.length} doctor profiles`);

  // Prescriptions: use create() so pre-save hooks run (rxId generation, expiry check)
  const rx1 = await Prescription.create({
    createdBy:  insertedDoctors[0]._id,
    createdFor: insertedPatients[0]._id,
    diagnosis:  'Hypertension',
    symptoms:   ['Headache', 'Dizziness', 'Blurred vision'],
    medicines: [
      { name: 'Amlodipine',   dosage: '5mg',  frequency: 'Once daily', duration: '30 days', instructions: 'Take in the morning' },
      { name: 'Telmisartan',  dosage: '40mg', frequency: 'Once daily', duration: '30 days', instructions: 'Take with or without food' },
    ],
    advice: 'Reduce salt intake. Exercise 30 minutes daily.',
    status: 'active',
  });

  const rx2 = await Prescription.create({
    createdBy:  insertedDoctors[1]._id,
    createdFor: insertedPatients[1]._id,
    diagnosis:  'Eczema',
    symptoms:   ['Itching', 'Dry skin', 'Redness'],
    medicines: [
      { name: 'Hydrocortisone cream 1%', dosage: 'Thin layer', frequency: 'Twice daily', duration: '14 days', instructions: 'Apply to affected area only' },
      { name: 'Cetirizine', dosage: '10mg', frequency: 'Once daily at night', duration: '14 days' },
    ],
    advice: 'Moisturize regularly. Avoid hot water baths.',
    status: 'active',
  });

  const rx3 = await Prescription.create({
    createdBy:  insertedDoctors[2]._id,
    createdFor: insertedPatients[2]._id,
    diagnosis:  'Type 2 Diabetes — Follow-up',
    symptoms:   ['Fatigue', 'Frequent urination', 'Increased thirst'],
    medicines: [
      { name: 'Metformin', dosage: '500mg', frequency: 'Twice daily', duration: '90 days', instructions: 'Take with meals' },
      { name: 'Glipizide', dosage: '5mg',   frequency: 'Once daily before breakfast', duration: '90 days' },
    ],
    labTests:     ['HbA1c', 'Fasting Blood Sugar', 'Post-prandial Blood Sugar', 'Lipid Profile'],
    advice:       'Monitor blood sugar twice daily. Low carb diet. Walk 45 min/day.',
    followUpDate: new Date(Date.now() + 90 * 24 * 60 * 60 * 1000),
    status: 'active',
  });

  logger.info(`Inserted 3 prescriptions (rxIds: ${rx1.rxId}, ${rx2.rxId}, ${rx3.rxId})`);

  // Consultations: use create() so roomId is auto-generated by pre-save hook
  const c1 = await Consultation.create({
    patient:    insertedPatients[0]._id,
    doctor:     insertedDoctors[0]._id,
    status:     'completed',
    reason:     'High blood pressure follow-up',
    startedAt:  new Date(Date.now() - 2 * 24 * 60 * 60 * 1000),
    endedAt:    new Date(Date.now() - 2 * 24 * 60 * 60 * 1000 + 25 * 60 * 1000),
    duration:   25,
    prescription: rx1._id,
    review:     { rating: 5, comment: 'Excellent doctor! Very thorough and knowledgeable.' },
  });

  const c2 = await Consultation.create({
    patient:      insertedPatients[1]._id,
    doctor:       insertedDoctors[1]._id,
    status:       'active',
    reason:       'Skin rash on forearms',
    startedAt:    new Date(),
    prescription: rx2._id,
  });

  const c3 = await Consultation.create({
    patient: insertedPatients[2]._id,
    doctor:  insertedDoctors[2]._id,
    status:  'active',
    reason:  'Diabetes management and medication review',
    startedAt: new Date(),
  });

  logger.info(`Inserted 3 consultations (roomIds: ${c1.roomId}, ${c2.roomId}, ${c3.roomId})`);

  // Seed some messages into the active consultation
  const patientUser = insertedUsers[1];   // patient2
  const doctorUser  = insertedUsers[4];   // doctor2

  await Message.insertMany([
    {
      consultation: c2._id,
      sender:       patientUser._id,
      senderRole:   'patient',
      text:         'Hello Dr. Kapoor, I have a rash on my forearms that has been itching badly for 3 days.',
      isRead:       true,
      createdAt:    new Date(Date.now() - 10 * 60 * 1000),
    },
    {
      consultation: c2._id,
      sender:       doctorUser._id,
      senderRole:   'doctor',
      text:         'Hello Priya, thank you for reaching out. Can you describe the appearance? Is it red, raised, or blistering?',
      isRead:       true,
      createdAt:    new Date(Date.now() - 8 * 60 * 1000),
    },
    {
      consultation: c2._id,
      sender:       patientUser._id,
      senderRole:   'patient',
      text:         'It is red and slightly raised. Not blistering but very dry around the edges.',
      isRead:       false,
      createdAt:    new Date(Date.now() - 5 * 60 * 1000),
    },
  ]);

  logger.info('Inserted sample messages');
  logger.info('\n✅ Database seeded successfully!\n');
  logger.info('Demo credentials:');
  logger.info('  Patient: patient1@medilink.com / pass123');
  logger.info('  Doctor:  doctor1@medilink.com  / pass123');
};

const cleanData = async () => {
  logger.info('Cleaning database…');
  await Promise.all([
    User.deleteMany({}),
    Patient.deleteMany({}),
    Doctor.deleteMany({}),
    Prescription.deleteMany({}),
    Consultation.deleteMany({}),
    Message.deleteMany({}),
  ]);
  logger.info('✅ All collections cleared');
};

const showStatus = async () => {
  const [u, p, d, rx, c, m] = await Promise.all([
    User.countDocuments(),
    Patient.countDocuments(),
    Doctor.countDocuments(),
    Prescription.countDocuments(),
    Consultation.countDocuments(),
    Message.countDocuments(),
  ]);
  console.table({ Users: u, Patients: p, Doctors: d, Prescriptions: rx, Consultations: c, Messages: m });
};

(async () => {
  try {
    await connect();
    const arg = process.argv[2];
    if      (arg === '--seed')   { await cleanData(); await seedData(); }
    else if (arg === '--clean')  { await cleanData(); }
    else if (arg === '--status') { await showStatus(); }
    else { console.log('Usage: node seeder.js [--seed | --clean | --status]'); }
  } catch (err) {
    logger.error(`Seeder error: ${err.stack || err.message}`);
    process.exit(1);
  } finally {
    await mongoose.disconnect();
    process.exit(0);
  }
})();
